version: '3.4'

services:
  ocelotgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  studentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  teacherservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

